openapi: 3.0.0
servers:
  - url: 'https://2wderi5mvk.execute-api.eu-central-1.amazonaws.com/TestProjectsAPI'
info:
  description: See [SDO Harmonized Interfaces](https://bitbucket.org/sdo-hapi/) for more information about this API
  version: 1.1.1
  title: NEN Projects API
tags:
  - name: Projects
    description: Projects API
paths:
  /projects:
    get:
      tags:
        - Projects
      summary: Search projects
      operationId: searchProjectsUsingGET
      parameters:
        - name: q
          in: query
          description: the search query
          required: true
          allowEmptyValue: false
          schema:
            type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad request (parameters syntax or semantics)
          
  '/projects/{urn}':
    get:
      tags:
        - Projects
      summary: Retrieve a specific project by its URN
      operationId: getProjectUsingGET
      parameters:
        - name: urn
          in: path
          description: the project URN
          required: true
          schema:
            type: string
          allowReserved: true
      responses:
        '200':
          description: Project found
        '404':
          description: Project not found
